language: python
sudo: true
dist: xenial
python:
  - "3.8"
  - "3.7"
  - "3.6"
  - "3.5"
  - "3.4"
install:
  - pip install codecov
  - pip install -e ".[test]"
script:
  - bin/test.sh
after_success:
  - codecov