language: python
sudo: true
dist: jammy
python:
  - "3.12"
  - "3.11"
  - "3.10"
install:
  - pip install codecov
  - pip install "cython>=3.0"
  - pip install -e ".[test]"
script:
  - bin/test -u
after_success:
  - codecov