/* This file is autogenerated by generate_sparsetools.py
 * Do not edit manually or check into VCS.
 */
NPY_VISIBILITY_HIDDEN PyObject *rbm_matmat_pass1_method(PyObject *, PyObject *);
NPY_VISIBILITY_HIDDEN PyObject *rbm_matmat_pass2_method(PyObject *, PyObject *);

static struct PyMethodDef sparsetools_methods[] = {
        {"rbm_matmat_pass1", (PyCFunction)rbm_matmat_pass1_method, METH_VARARGS, NULL},
        {"rbm_matmat_pass2", (PyCFunction)rbm_matmat_pass2_method, METH_VARARGS, NULL},
        {NULL, NULL, 0, NULL}
    };