# Util subpackage - pure Python

python_sources = [
  '__init__.py',
  'abstract_graph.py',
  'capture.py',
  'graph_builder.py',
  'names.py',
  'relationship_db_reader.py',
  'relationship_file_io.py',
  'synthesizer.py',
  'test_support.py',
]

py.install_sources(
  python_sources,
  subdir: 'redblackgraph/util'
)
