name: Build and Publish Wheels

on:
  # Run on version tags
  push:
    tags:
      - 'v*.*.*'
  # Allow manual trigger
  workflow_dispatch:
    inputs:
      publish_to:
        description: 'Publish to (none/testpypi/pypi)'
        required: true
        default: 'none'
        type: choice
        options:
          - none
          - testpypi
          - pypi

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13, macos-14]  # macos-13 is x86_64, macos-14 is arm64

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for setuptools_scm to detect version from tags

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.5
        env:
          # Pass through any needed environment variables
          CIBW_BUILD_VERBOSITY: 1

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for setuptools_scm to detect version from tags

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build sdist
        run: python -m build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-sdist
          path: dist/*.tar.gz

  publish:
    name: Publish to PyPI
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    # Only publish on tag pushes or manual workflow with publish_to set
    if: |
      (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')) ||
      (github.event_name == 'workflow_dispatch' && inputs.publish_to != 'none')
    
    permissions:
      id-token: write  # For trusted publishing to PyPI
      
    environment:
      name: ${{ github.event_name == 'workflow_dispatch' && inputs.publish_to || 'pypi' }}
      url: ${{ 
        github.event_name == 'workflow_dispatch' && inputs.publish_to == 'testpypi' 
        && 'https://test.pypi.org/p/redblackgraph' 
        || 'https://pypi.org/p/redblackgraph' 
      }}

    steps:
      - uses: actions/download-artifact@v4
        with:
          # Download all artifacts
          pattern: cibw-*
          path: dist
          merge-multiple: true

      - name: List artifacts
        run: ls -lh dist/

      # Publish to Test PyPI
      - name: Publish to Test PyPI
        if: |
          (github.event_name == 'workflow_dispatch' && inputs.publish_to == 'testpypi')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

      # Publish to PyPI
      - name: Publish to PyPI
        if: |
          (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')) ||
          (github.event_name == 'workflow_dispatch' && inputs.publish_to == 'pypi')
        uses: pypa/gh-action-pypi-publish@release/v1
